#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.chef_zero')" != "$CHEF_ZERO_VERSION" ]]; then
    return 1
  fi

  return 0
}

main "$@"
