#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  for nm_service in "$@"; do
    case "$nm_service" in
      default)
        exec chef-zero
        ;;
    esac
  done
}

main "$@"

