#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_chef_zero="0.0.1"
  jq -n --arg chef_zero "$ver_chef_zero" '{chef_zero: $chef_zero}'
}

version "$@"
